
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Akash
 */
public class ownerInfoDisplay extends javax.swing.JFrame {
    String owid;
       public ownerInfoDisplay(String oid) {
             owid=oid;
          
        
       initComponents();
       setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
           FillCombo();
           
           ret();
           txtOid.setText(owid);
           txtOid.setEditable(false);
       
        txtFatherName.setEditable(false);
        txtDOB.setEditable(false);
        txtPhone.setEditable(false);
        txtName.setEditable(false);
        taAddress.setEditable(false);
         
    }
    /**
     * Creates new form ownerVehicleReg
     */
    public ownerInfoDisplay() {
       
        
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }
    private void FillCombo()
    {   PreparedStatement st=null;
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull","root","14011996");
             //String name=rs.getString("v_id");
             System.out.println(owid);
             st=con.prepareStatement("select * from registration where cus_id=?");
              st.setString(1,owid);
              System.out.println("545");
             ResultSet rs=st.executeQuery();
             ///String name=rs.getString("veh_no");
             //System.out.println(name);
            //st=con.prepareStatement("select * from registration where veh_no=?");
            //st.setString(1,name);
            //rs=st.executeQuery();
            while(rs.next())
            {
                cb.addItem(rs.getString("veh_no"));
            }
        
        
        } catch (SQLException ex) {
            Logger.getLogger(ownerInfoDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ret()
    {
        PreparedStatement stm=null;
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull","root","14011996");
             stm=con.prepareStatement("Select * from owner where owner_id=?" );
          stm.setString(1,owid);
             System.out.println("123");
             ResultSet rs1=stm.executeQuery();
             //System.out.println(rs1.getString("name"));
             
             while(rs1.next())
             {   System.out.println("123");
                 txtName.setText(rs1.getString("name"));
                 txtDOB.setText(rs1.getString("dob"));
                 txtOid.setText(rs1.getString("owner_id"));
                 txtFatherName.setText(rs1.getString("father_name"));
                 taAddress.setText(rs1.getString("address"));
                 txtPhone.setText(rs1.getString("phone"));
             }
             
        
        
        } catch (SQLException ex) {
            Logger.getLogger(ownerInfoDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFatherName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtOid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        txtFatherName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFatherNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFatherName);
        txtFatherName.setBounds(1000, 350, 589, 50);

        txtDOB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        getContentPane().add(txtDOB);
        txtDOB.setBounds(1000, 290, 589, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("VEHICLE ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 640, 186, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("OWNER INFORMATION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 60, 564, 58);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("ADDRESS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 490, 152, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("OWNER ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 160, 171, 44);

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone);
        txtPhone.setBounds(1000, 420, 589, 50);

        txtOid.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtOid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOidActionPerformed(evt);
            }
        });
        getContentPane().add(txtOid);
        txtOid.setBounds(1000, 150, 589, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("PHONE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 430, 113, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 220, 94, 44);

        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        taAddress.setRows(5);
        jScrollPane1.setViewportView(taAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1000, 490, 589, 117);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(1000, 220, 589, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("DATE OF BIRTH");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 290, 254, 44);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("FATHER'S NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 360, 261, 44);

        cb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        getContentPane().add(cb);
        cb.setBounds(1000, 640, 589, 50);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(880, 740, 163, 61);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit Akash\\Desktop\\dbms project\\19111808-Proud-new-car-owner-Stock-Vector.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 50, 1590, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFatherNameActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtOidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOidActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // txtOid.setText(owid);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerInfoDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerInfoDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerInfoDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerInfoDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerInfoDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOid;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
