/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Akash
 */
public class startup extends javax.swing.JFrame {
    String name;
    /**
     * Creates new form startup
     */
    public startup() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }
     public startup(String n) {
        name=n;
         initComponents();
         setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
         l1.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnChgOwn = new javax.swing.JButton();
        btnOwnInfo = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        btnTaxInfo = new javax.swing.JButton();
        btnVehInfo = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1980, 1080));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("VEHICLE REGISTRATION MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 140, 1063, 209);

        btnChgOwn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnChgOwn.setText("TO CHANGE OWNERSHIP");
        btnChgOwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgOwnActionPerformed(evt);
            }
        });
        getContentPane().add(btnChgOwn);
        btnChgOwn.setBounds(170, 520, 550, 97);

        btnOwnInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnOwnInfo.setText("OWNER INFO");
        btnOwnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOwnInfoMouseClicked(evt);
            }
        });
        btnOwnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnOwnInfo);
        btnOwnInfo.setBounds(860, 520, 530, 95);

        btnReg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnReg.setText("CLICK HERE TO REGISTER");
        btnReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegMouseClicked(evt);
            }
        });
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg);
        btnReg.setBounds(850, 360, 550, 97);

        btnTaxInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnTaxInfo.setText("TAX DETAILS");
        btnTaxInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaxInfoMouseClicked(evt);
            }
        });
        btnTaxInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTaxInfo);
        btnTaxInfo.setBounds(540, 670, 500, 100);

        btnVehInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnVehInfo.setText("VEHICLE INFO");
        btnVehInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehInfoMouseClicked(evt);
            }
        });
        btnVehInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVehInfo);
        btnVehInfo.setBounds(160, 370, 560, 97);

        l1.setBackground(new java.awt.Color(102, 102, 102));
        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(l1);
        l1.setBounds(150, 20, 200, 20);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("WELCOME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit Akash\\Desktop\\dbms project\\front.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, -70, 1840, 320);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit Akash\\Desktop\\dbms project\\front1.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1500, 180, 300, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehInfoActionPerformed
        // TODO add your handling code here:
        vehicle2 vinfo=new vehicle2();
        vinfo.setVisible(true);
    }//GEN-LAST:event_btnVehInfoActionPerformed

    private void btnVehInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehInfoMouseClicked
        // TODO add your handling code here:
           
           //startup s=new startup();
          // s.dispose();
           
    }//GEN-LAST:event_btnVehInfoMouseClicked

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
                        // TODO add your handling code here:
                        new option().setVisible(true);
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnTaxInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaxInfoMouseClicked
        // TODO add your handling code here:
        tax tax=new tax();
        tax.setVisible(true);
    }//GEN-LAST:event_btnTaxInfoMouseClicked

    private void btnRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegMouseClicked
        // TODO add your handling code here:
           
    }//GEN-LAST:event_btnRegMouseClicked

    private void btnOwnInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOwnInfoMouseClicked
        // TODO add your handling code here:
        owner onr=new owner();
        onr.setVisible(true);
    }//GEN-LAST:event_btnOwnInfoMouseClicked

    private void btnOwnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOwnInfoActionPerformed

    private void btnChgOwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgOwnActionPerformed
            // TODO add your handling code here:
        ChangeOwner noi=new ChangeOwner();
        noi.setVisible(true);
    }//GEN-LAST:event_btnChgOwnActionPerformed

    private void btnTaxInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaxInfoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
                //new startup().setSize(1650,1080);
setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChgOwn;
    private javax.swing.JButton btnOwnInfo;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnTaxInfo;
    private javax.swing.JButton btnVehInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
