
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Akash
 */
public class vehicle extends javax.swing.JFrame {
int flag=0;
String id;
    
    public vehicle(int f,String v_id)
{
    flag=f;
    id=v_id;
    if(flag==1)
    {   initComponents();
    setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        details();
    }
}
    private void details()
    {
       PreparedStatement stm = null ;
       if(flag==1)
       {
           try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull","root","14011996");
            stm=con.prepareStatement("Select * from vehicle where v_id = ?");
            stm.setString(1,id);
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                txtVid.setText(rs.getString("v_id"));
                txtModel.setText(rs.getString("model"));
                txtColour.setText(rs.getString("colour"));
                txtManYear.setText(rs.getString("man_year"));
                txtFuelType.setText(rs.getString("fuel_type"));
                txtCompany.setText(rs.getString("company"));
                txtPrice.setText(rs.getString("price"));
                txtType.setText(rs.getString("type"));
            }
           } catch (SQLException ex) {
               Logger.getLogger(vehicle.class.getName()).log(Level.SEVERE, null, ex);
           }
            //Class.forName("com.mysql.jdbc.Driver"); 
           
           
           
       }
    }
    /**
     * Creates new form vehicle
     */
    public vehicle() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtColour = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFuelType = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtManYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();

        getContentPane().setLayout(null);

        txtPrice.setEditable(false);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice);
        txtPrice.setBounds(1040, 730, 440, 41);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COMPANY");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 660, 162, 44);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PRICE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 730, 97, 44);

        txtVid.setEditable(false);
        txtVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidActionPerformed(evt);
            }
        });
        getContentPane().add(txtVid);
        txtVid.setBounds(1040, 270, 440, 44);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VEHICLE ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 270, 186, 44);

        txtColour.setEditable(false);
        txtColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColourActionPerformed(evt);
            }
        });
        getContentPane().add(txtColour);
        txtColour.setBounds(1040, 400, 440, 43);

        txtType.setEditable(false);
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txtType);
        txtType.setBounds(1040, 460, 440, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 330, 115, 44);

        txtFuelType.setEditable(false);
        txtFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuelType);
        txtFuelType.setBounds(1040, 600, 440, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COLOUR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 400, 136, 44);

        txtManYear.setEditable(false);
        txtManYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtManYear);
        txtManYear.setBounds(1040, 530, 440, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TYPE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 450, 82, 44);

        txtCompany.setEditable(false);
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });
        getContentPane().add(txtCompany);
        txtCompany.setBounds(1040, 660, 440, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MANUFACTURE YEAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 520, 344, 44);

        txtModel.setEditable(false);
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        getContentPane().add(txtModel);
        txtModel.setBounds(1040, 340, 440, 42);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FUEL TYPE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 590, 174, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setText("VEHICLE DETAILS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 170, 480, 58);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(850, 820, 200, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vehicle-management.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, -100, 2590, 1160);
        getContentPane().add(jDayChooser1);
        jDayChooser1.setBounds(580, 300, 182, 133);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidActionPerformed

    private void txtColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColourActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelTypeActionPerformed

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtManYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtManYear;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVid;
    // End of variables declaration//GEN-END:variables
}
